server:
port: 8080

mybatis:
type-aliases-package: com.acorn.springboardstudy.dto
# mybatis Mapper.xml 에서 패키지 경로를 먼저 설정해두면 resultMap 의 Type 에 경로 안적어도 된다!
mapper-locations: mapper/*Mapper.xml
# mybatis 경로 설정하는 application.yml 파일을 위치 기준으로 경로 작성 - 보통 resources 폴더 안에 만든다.
# *Mapper.xml => 복수인 이유는 Mapper.xml 파일이 여러개이니까
# type-aliases-package: 패키지명 설정 / Mapper.xml 파일에서 com.acron.springmavenboard.dto 패키지명을 생략할 수있다.

# 페이징을 만들어주는 라이브러리. 쿼리를 자동생성해준다.
pagehelper:
helper-dialect: mysql
reasonable: true
